commonLabels:
  app.kubernetes.io/genereted-by: JHipster

namespace: mspr4

resources:
  - namespace.yml
  # Individual apps
  - kawavendorapi-k8s/kawavendorapi-deployment.yml
  - kawavendorapi-k8s/kawavendorapi-service.yml
  - kawavendorapi-k8s/kawavendorapi-postgresql.yml
  - kawavendorapi-k8s/kawavendorapi-prometheus-sm.yml
  # monitoring prometheus
  - monitoring-k8s/jhipster-prometheus-cr.yml
  - monitoring-k8s/jhipster-prometheus-crd.yml
  - monitoring-k8s/jhipster-grafana.yml
  - monitoring-k8s/jhipster-grafana-dashboard.yml
  # service discovery eureka/consul
  - registry-k8s/jhipster-registry.yml
  - registry-k8s/application-configmap.yml

patchesJson6902:
