---
version: '3.8'
services:
  prism:
    image: stoplight/prism:4
    command: 'mock -h 0.0.0.0 /central-config/localhost-config/data-openapi.yml'
    volumes:
      - ./central-server-config:/central-config
    ports:
      # Serve the mocked API locally as available on port 8080
      - '8079:4010'
