<!DOCTYPE html>
<html lang="fr">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <title></title>
    <style>
        body {
            font-family: Arial, Helvetica, sans-serif;
            background-color: #f0f0f0;
        }

        h3 {
            color: #333333;
            font-weight: bold;
        }

        p {
            color: #666666;
        }

        span {
            color: #ff6600;
            font-style: italic;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            padding: 20px;
        }

        td {
            text-align: center;
        }
    </style>
</head>
<body>
<p>Bonjour ${name}</p>
</body>

</html>
