apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: replace-data
spec:
  params:
  - name: from
    type: string
  - name: to
    type: string
  - name: file
    type: string
  workspaces:
  - name: source
  steps:
  - name: replace-token
    image: bash:latest
    script: | 
      #!/usr/bin/env bash
      apk add --update --no-cache sed
      cd $(workspaces.source.path)
      sed -i 's/$(params.from)/$(params.to)/g' $(params.file)
